# Generated by Django 6.0.5 on 2026-05-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='p_quality',
            new_name='p_quantity',
        ),
    ]
